### ISSUE TITLE
Custom integration in hiera

### ISSUE THREAD

**Issue by jeandoBet** [DataDog/puppet-datadog-agent#670]
Hi, 

This is surely not an issue, but i'm having troubles to add an integration from yaml.

It works fine when i call it in my class : 

    class { 'datadog_agent':
     [...]
     hiera_integrations    => true,

    integrations => {
      "iis" => {
        init_config => {},
          instances => [{
            host => '.',
          }],
          logs => [{
            path           => 'C:/HTTPERR/*.log',
            service        => 'iis',
            source         => 'iis',
            sourcecategory => 'http_web_access',
            type           => 'file',
          },{
            path           => 'C:/logs/*.log',
            service        => 'iis',
            source         => 'iis',
            sourcecategory => 'http_web_access',
            type           => 'file',
          }],
      },
    },
    }
    } 

I would like to do the same, but in yaml. 

I tried this, but nothing happens :
```
datadog_agent::integrations::iis::init_config: {}
  datadog_agent::integrations::iis::instances:
  - host: '.'
datadog_agent::integrations::iis::logs:
  - path: 'C:/HTTPERR/*.log'
    service: 'iis'
    source: 'iis'
    sourcecategory: 'http_web_access'
    type: 'file'
  - path: 'C:/logs/*.log'
    service: 'iis'
    source: 'iis'
    sourcecategory: 'http_web_access'
    type: 'file' test
```

what am i missing ?

**Comment by jeandoBet** [comment]
Fixed, here is the syntax : 

```
datadog_agent::integrations:
  iis:
    init_config: {}
    instances:
      - host: '.'
    logs:
      - path: 'C:/HTTPERR/*.log'
        service: 'iis'
        source: 'iis'
        sourcecategory: 'http_web_access'
        type: 'file'
      - path: 'C:/logs/*.log'
        service: 'iis'
        source: 'iis'
        sourcecategory: 'http_web_access'
        type: 'file'
```
