### ISSUE TITLE
backslash issue in custom integrations

### ISSUE THREAD

**Issue by jeandoBet** [DataDog/puppet-datadog-agent#671]
Hi, i'm trying to fix a custom integration that contains a backslash "\" . It seems that the ruby script (to_instances_yaml.rb) doubles the backslash.

Here's my conf : 

```
datadog_agent::integrations:
  custom_logs:
    init_config:
    instances: []
    logs:
      - path: 'C:/temp/*.log'
        service: 'grokerror'
        source: 'custom_logs'
        type: 'file'
        log_processing_rules:
          name: 'log_start'
          pattern: '\|\]'
          type: 'multi_line'
```

Here is the output I have in my custom_logs.d/conf.yaml : 
```
[...]
          pattern: "\\|\\]"
[...]
```

(And if I set two backslash's, I get four of them in the output..)

Any idea how i could bypass this ? 

Thanks,
