### ISSUE TITLE
Support runtime security

### ISSUE THREAD

**Issue by djtecha** [DataDog/puppet-datadog-agent#702]
Hello all,
with the new release of the security agent it looks like we have no way to enable this using this module. Need to manage the security-agent.yaml and have additional settings in the system-probe.yaml so we can add things like this:

```
runtime_security_config:
  enabled: true
  fim_enabled: true
  syscall_monitor:
    enabled: true
```
